# config.nu — Nushell shell config
# Loaded after env.nu on every interactive shell start

# --- Source pre-generated inits ---
const nu_config_dir = $nu.default-config-dir

# These files are generated by `setup.nu init` (starship init nu / zoxide init nushell).
# Create empty stubs so `source` doesn't fail before they've been generated.
const starship_nu = ($nu_config_dir | path join "starship.nu")
const zoxide_nu  = ($nu_config_dir | path join "zoxide.nu")
const opencode_nu = ($nu_config_dir | path join "opencode.nu")

source $starship_nu
source $zoxide_nu
if ($opencode_nu | path exists) { source $opencode_nu }

# --- Shell settings ---
$env.config.show_banner = false
$env.config.history = {
    max_size: 10000
    sync_on_enter: true
    file_format: "sqlite"
}
$env.config.completions = {
    case_sensitive: false
    quick: true
    partial: true
    algorithm: "fuzzy"
}
$env.config.cursor_shape = {
    emacs: "line"
    vi_insert: "line"
    vi_normal: "block"
}

# --- Aliases ---
alias cat = bat --paging=never
alias lg = lazygit
alias ld = lazydocker

# --- Custom commands ---

# Create a directory and cd into it
def --env mkcd [path: string] {
    mkdir $path
    cd $path
}

# Find a file with fd and jump to its directory with zoxide
def fdz [name: string] {
    let result = (fd --color=never --type f $name | lines | first)
    if ($result | is-empty) {
        print "File not found."
        return
    }
    z ($result | path dirname)
}

# Get public IP
def pubip [] {
    http get http://ifconfig.me/ip | str trim
}

# Compile and run C file
def ccr [file: string, ...args: string] {
    let out = ($file | str replace ".c" "")
    cc $file -o $out ...$args
    ^$"./($out)"
}

# Bare-repo worktrees: <repo>/.bare holds git, each branch gets a <repo>/<branch> folder.
def gwt [] { help gwt }

# Clone a repo bare, check out its default branch as the first worktree, and cd into it
def --env "gwt clone" [url: string, dir?: string] {
    let name = $url | str trim --right --char '/' | path basename | str replace -r '\.git$' ''
    let root = $dir | default $name | path expand
    git clone --bare $url ($root | path join .bare)
    "gitdir: ./.bare\n" | save ($root | path join .git)
    # Bare clones have no fetch refspec, so origin/* would never update.
    git -C $root config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git -C $root fetch origin
    let branch = git -C $root symbolic-ref --short HEAD | str trim
    let dest = $root | path join ($branch | str replace -a '/' '-')
    git -C $root worktree add $dest $branch
    git -C $dest branch --quiet --set-upstream-to $"origin/($branch)"
    cd $dest
}

# Add a worktree for a branch and cd into it. New branches start from origin's default branch (or --from).
def --env "gwt add" [branch: string, --from (-f): string] {
    let common = git rev-parse --path-format=absolute --git-common-dir | str trim
    let dest = $common | path dirname | path join ($branch | str replace -a '/' '-')
    git fetch origin
    let has = {|ref| (^git show-ref --verify --quiet $ref | complete).exit_code == 0 }
    let on_origin = do $has $"refs/remotes/origin/($branch)"
    if $on_origin or (do $has $"refs/heads/($branch)") {
        git worktree add $dest $branch
        # Bare clones copy remote branches as plain local ones, without tracking.
        if $on_origin { git -C $dest branch --quiet --set-upstream-to $"origin/($branch)" }
    } else {
        let base = $from | default (git --git-dir $common symbolic-ref --short HEAD | str trim)
        git worktree add --no-track -b $branch $dest $"origin/($base)"
    }
    cd $dest
}
